### ISSUE TITLE
Generic Structure

### ISSUE THREAD

**Issue by davidhund** [webpro/component-styleguide#1]
Hey Lars, I like the generic, unopinionated, feel of this and wonder how easy it would be to make this _more_ generic. Would it be a lot of work to lose the requirement of an 'atomic' structure or add a new category of 'generic' components?

Although I like the PatternLab structure of 'atoms', 'molecules', 'organisms', 'pages' etc. not all (existing) projects are a great fit. For those I'd like to have, say, a generic '/components' folder in which I could place generic components (nested subfolders).

**Comment by webpro** [comment]
Thanks for checking it out, @davidhund. I like your idea and I'm happy to accept a PR for this,or make the change myself soon. Have some ideas already :-)

**Comment by webpro** [comment]
Hey @davidhund, just released v1.2.0 which should contain what you proposed. It now reads all templates from the root and all subfolders, and creates menu items for each. The "root" or "generic" components menu item name can be configured with `rootName`.

It does not support deeply nested folders (yet), just child folders within the `/components` folder.

Let me know if it works for you. Thanks again for the idea.

**Comment by davidhund** [comment]
Just playing around it seems to do exactly what I wanted. Awesome work. 
It's simple and flexible and does not force me in a specific workflow/process.

Now to find a way to extract the HTML markup from my (s)CSS comments (much like KSS) so that the markup is not disconnected from the 'source' CSS :)

**Comment by webpro** [comment]
Thanks for the feedback! Let me know if you have any more ideas.

(Regarding the CSS parsing, not sure. The simplest method that could work might be to use [a CSS parser](https://github.com/reworkcss/css) and have it write the comments from the AST to HTML files in the "components" dir.)

**Comment by davidhund** [comment]
Yeah. I am really looking forward to a standardized CSS Comment(!) Parser. 
https://twitter.com/valuedstandards/status/582504525455560704

Something like https://github.com/darcyclarke/DSS could work. This would prevent us from having to maintain markup in multiple places...

**Comment by webpro** [comment]
Ah DSS looks nice. Totally JSDoc-y and useful with those `@name` and `@markup` tags etc.

**Comment by webpro** [comment]
Closing this, as the initial issue is taken care of.
