### ISSUE TITLE
Component menus unusable when taking up too much vertical space

### ISSUE THREAD

**Issue by jaasum** [webpro/component-styleguide#4]
I am working on a styleguide that has around 34 items in the "atoms" component folder. When on a laptop screen a decent amount of these items get cut off of the list and I am unable to navigate to them using the menu.

You cannot scroll the page while in the menu.

![screen shot 2015-11-04 at 3 25 08 pm](https://cloud.githubusercontent.com/assets/180139/10955394/430dfc18-8308-11e5-9415-c55feed74906.png)

**Comment by webpro** [comment]
For now, I have added some CSS so the items are at least scrollable. Not perfect, but at least you should be able to reach each item. Released in v1.3.0.  Please let me know how it works for you.

**Comment by jaasum** [comment]
Works great! Thank you.
