### ISSUE TITLE
Possible to nest components?

### ISSUE THREAD

**Issue by jaasum** [webpro/component-styleguide#5]
I tried to nest a component (say components > atoms > buttons > button.html button-secondary.html etc) and the menu properly displayed Button/Button and Button/Button Secondary, however you're met with a "File not found" message when trying to navigate. 

Ideally you have a way to group components, and simplify the browsing experience to navigate to grouped components.

**Comment by webpro** [comment]
Totally agree with the request, I'll look into this tomorrow.

**Comment by webpro** [comment]
I made a fix so the components should render properly. However, no nested menu levels (maybe later). Released in v1.3.0. Please let me know how it works for you.

**Comment by jaasum** [comment]
Works great! Thank you for the quick turnaround.
