### ISSUE TITLE
If a static resource begins with http(s), don’t prepend staticPath

### ISSUE THREAD

**Issue by paulrobertlloyd** [webpro/component-styleguide#6]
I’m trying to add live reload functionality. To do so, I’ve added a command to my build script to start livereload server on port 9091. Of course, I then need to link to the livereload.js script. So I did the following in index.js:

``` js
var styleguide = require('component-styleguide'),
    path = require('path');

styleguide({
    components: path.resolve(__dirname, 'components'),
    ext: 'html',
    data: path.resolve(__dirname, 'data'),
    staticLocalDir: path.resolve(__dirname, 'compiled'),
    staticPath: '/compiled',
    stylesheets: ['app.css'],
    scripts: ['http://localhost:9091','app.js']
});
```

Unfortunately, this generates the following HTML:

``` html
<script src="/compiled/http://localhost:9091"></script>
<script src="/compiled/app.js"></script>
```

I tried changing `staticPath:` to  `''`, and add this path to each stylesheet and script individually, but this had no effect. Adding a resource to the `scripts` or `stylesheets` arrays that starts with `http://` or `https://`, the `staticPath` value should be ignored… unless there is another way of achieving the desired result?

**Comment by webpro** [comment]
This should work properly (paths starting with "http" are used as-is) from v1.3.1.

**Comment by paulrobertlloyd** [comment]
Fantastic, thanks for the quick turnaround!
