### ISSUE TITLE
Ability to define default data source

### ISSUE THREAD

**Issue by paulrobertlloyd** [webpro/component-styleguide#8]
It would be helpful to have a place to define default data, for partials that have not been given a context. i.e. given the following template:

```
<h1>{{ headingText }}</h1>
```

and the following data (possibly in a `data/data.json` file, or in a location defined in the configuration options):

``` json
{
    "headingText": "This is a heading"
}
```

the following would result:

```
<h1>This is a heading</h1>
```

Having such a function would mean authors could avoid scenarios where templates need to be written as such:

```
<h1>{{#if headingText}}{{headingText}}{{else}}This is a heading{{/if}}</h1>
```

**Comment by webpro** [comment]
Apologies for the late reply, @paulrobertlloyd. Are things working fine for you? Maybe PR #12 helps with this? Feel free to re-open!

**Comment by paulrobertlloyd** [comment]
The addition in #12 looks very helpful. Will check it out and report back if I face any issues. Thanks!
